### ISSUE TITLE
Feature Suggestion: Constructor from list of numpy

### ISSUE THREAD

**Issue by nerduno** [soft-matter/pims#139]
In addition to having the TiffStack, Video, and ImageSequence constructors, it would be convenient to be able to construct from a sequence of numpy arrays in memory.

**Comment by danielballan** [comment]
If everything is in memory already, you might as well do this:

```
from pims import Frame
v = list(map(Frame, sequence_of_numpy_arrays))
```

Granted we need documentation to make this clear.

**Comment by nerduno** [comment]
Perfect.   Thank you.

**Comment by tacaswell** [comment]
That does not get you fancy slicing though, only normal list slicing.
