### ISSUE TITLE
Add more specialty readers...

### ISSUE THREAD

**Issue by danielballan** [soft-matter/pims#148]
* SPE reader (move from NSLS-II/filestore)
* EDF and other formats read by [fabio](https://github.com/kif/fabio)
* "Data Exchange" HDF5 -- see dxfile on binstar
* [https://github.com/tomopy/tomopy/blob/master/tomopy/io/exchange.py](tomopy's exchange module)

**Comment by tacaswell** [comment]
Also https://nexpy.github.io/nexpy/

**Comment by caspervdw** [comment]
Some basic ffmpeg support for people that can't install PyAv:
http://zulko.github.io/blog/2013/09/27/read-and-write-video-frames-in-python-using-ffmpeg/

**Comment by tacaswell** [comment]
I think we started the ffmpeg odyssey there and the problem with using pipes is that it is very hard to reliably get to frame `N` as ffmpeg has a looser idea of the importance of frames than we need for science (getting to about the 55s mark is good enough for seeking in a video a human is watching).  This is what drove Dan to the current implementation which reads the entire movie and stashes it uncompressed for later random access.

**Comment by danielballan** [comment]
Correct. I implemented something a lot like Zulko's code, MoviePy. It's still in PIMS as abandoned code in ffmpeg_reader. MoviePy is probably better though, so I'm all adding support for it.

**Comment by danielballan** [comment]
Also, Tom and I built conda packages for PyAV on Linux and OSX. A Windows one is not too far off.

**Comment by caspervdw** [comment]
What about OpenCV as a way to interface with ffmpeg? It's at least easy to install on a windows box using Christoph Gohlke's binaries.
I also had no problems with ImageIO (the reader MoviePy is based on) so I am :+1: for that option too.

**Comment by danielballan** [comment]
All of the above would be great. A couple years ago I had some problems getting random access to work reliably with OpenCV, but if it works in same cases we can support it with a disclaimer.

**Comment by caspervdw** [comment]
Another one: I coded up a bridge between pims and the nikon ND2SDK via ctypes, but it requires this order 100MB sdk and I only implemented it for win64 py2.7. Do you guys think this would be worthwile to put inside pims?

**Comment by danielballan** [comment]
Maybe a separate repo? I have a couple niche readers that I import separately.

**Comment by caspervdw** [comment]
Ok I will do that, maybe we could make a list of specialty readers in the docs, linking to the relevant repos.

**Comment by tacaswell** [comment]
:+1: On separate repo.  I suggest calling it `pims-nd2` and putting it under the soft-matter org.

**Comment by tacaswell** [comment]
Sounds like a plan!

**Comment by caspervdw** [comment]
There it is: https://github.com/caspervdw/pims_nd2
I don't have rights to create a repo under soft-matter, so maybe one of you guys could do that?

**Comment by tacaswell** [comment]
The easiest way to do this is to move the repo to me and then i can move it
up steam.

**Comment by caspervdw** [comment]
I requested the transfer, I guess you'll have to accept now.

**Comment by tacaswell** [comment]
@caspervdw https://github.com/soft-matter/pims_nd2
