### ISSUE TITLE
Roadmap for PIMS

### ISSUE THREAD

**Issue by danielballan** [soft-matter/pims#150]
Here are my thoughts on the near future of PIMS development.

Before tagging v0.3:
- Add a few more readers with associated optional dependencies.
- Remove the janky `plugin` argument from `ImageSequence`, and instead create separate classes (`ImageSequence_skimage`, `ImageSequence_mpl`, `ImageSequence_scipy`) the way we do for the variants of `TiffStack`. As with `TiffStack`, there will be a convenient `ImageSequence` alias pointing at the most reliable variant available.
- Merge #147 with recursive slicing and the new "pipeline" idea.

Then, once v0.3 is tagged, I'd like to make a more serious break change. If the pipelines are working well, I'd like to simplify all the built-in readers by removing `process_func`, `as_grey`, `dtype` as standard arguments. Any of those tasks -- and more -- can be accomplished more transparently and more generally by "pipeline" functions. I'd prefer the reader classes to be as lightweight and simple as possible. (Note that users could still implement their own readers that have a `process_func` arg or whatever they want; I'm just talking about the built-in readers here.)

With that major change in place, then I think it's time to tag 1.0.

Thoughts?

**Comment by danielballan** [comment]
@nkeim if you have time to read over this plan I'd like your input.

**Comment by caspervdw** [comment]
I think I am not long enough into pims to really comment on when to tag a release. But I would additionally like more homogeneous support for multidimensional files (Z, colorchannels, RGB channels). There are already 2 3D readers (`ImageSequence3D` and `Bioformats`) but it should be put in a more general wrapping.

Maybe something base_classes `FramesSequence3D`, `FramesSequenceMultichannel`, `FramesSequence3DMultichannel`.

This by the way is already being discussed inside https://github.com/soft-matter/pims/issues/124

**Comment by danielballan** [comment]
@caspervdw My goal with 1.0 is to correct API choices that were in retrospect not good and to commit to not breaking things for awhile. This does not preclude adding new functionality. Whether or not we get the desired 3D and color support into 1.0, I am open to issuing a 1.1 as soon as necessary.

What do you envision `FramesSequence3D` doing? I think of `FrameSequence` as N-dimensional, leaving to the the readers to do whatever they need to do in `__init__` and `get_frame`. Should we add something to `FramesSequence` to make that easier? I can see that the idea of "loop order" is important and maybe should work its way up. It's just not clear to me whether it should be a base class method or a shared utility function or something else.

**Comment by nkeim** [comment]
This sounds like a great approach to 1.0. `process_func` should definitely get the boot. But I'm less sure about `dtype` and `as_grey`. As pims becomes a pipeline construction kit, it needs to continue as a convenient scientific video reader. The two are not mutually exclusive, but I'd suggest that a few warts here and there might be desirable in the name of convenience.

That said, if getting rid of those keywords allows a radical simplification of the code… maybe my feelings are misguided. One compromise might be to override `ImageSequence.__new__()` to let `dtype` and `as_grey` invoke pipelines.

**Comment by caspervdw** [comment]
@danielballan The addition to `FramesSequence` would be *awareness* of the reader of the function of each dimension. It should define a blueprint for:

 - dimension size property
 - a custom `get_frame` that decides which indices along each axis are needed and uses `get_frame_2D(z, c, t, ...)` to aggregate one frame
 - properties `aggregate`, `loop_dimension` to determine what `get_frame` does

The reader should only need to define `get_frame_2D(*indices)` and the names and default uses of dimensions.

It may be better to rename it to `FramesDimensionAware`. I don't know if this is a base_class, it should go in between `FramesSequence` and any dimension-aware reader to standardize its use. I think it is good to do that before 1.0.

**Comment by danielballan** [comment]
OK, I'm sold. Something like `DimensionAwareFramesSequence` (not in love with that name) subclassing `FramesSequence`, to be subclassed by `ImageSequence3D` and similar.

**Comment by nkeim** [comment]
re: my earlier idea: my proposed `__new__()` scheme would cause an inconsistency with the child `close()` behavior we thought so hard about previously. So I'm out of ideas on how to accomplish this cleanly.

**Comment by danielballan** [comment]
In my research side-projects, I am finding the pipelines to be really useful. It's nice to have multiple references to the sequence at various stages of processing. As discussed in #156, the convenience kwarg is problematic on higher-dimensional data. A range of built-in pipeline functions would be more flexible. Existing users will have to transition to

    as_grey(ImageSequence('*.png'))

and users whose data does not work with our `as_grey` can look into

    pipeline(skimage.color.some_func)(ImageSequence('*.png'))

Are you persuaded, @nkeim?

I aim to tag 0.2.3 later this week, once #151 is in. Then, after a carefully reviewed PR that removes process_func, dtype, and as_grey from the built-in readers, I plan to tag 1.0 with no other changes.

I have no problem tagging many 1.x.y releases in rapid succession as people add useful readers. (There a couple I'm particularly interested in, but I don't want to hold up core pims over it.) Are we all on board with this plan?

**Comment by nkeim** [comment]
Persuaded! The convenience parameters are more costly than I originally thought. Too bad, though.

I have a useful (to me) reader more or less coded up, but not yet sufficiently tested. It will be nice to have a slimmer API to implement.

I guess the tutorials for trackpy v0.3 should be written for PIMS 1.0. Seems logical, but a little reckless.

**Comment by danielballan** [comment]
For v0.3:

* Rebase on Slicerator
* Make a reader class for numpy arrays

For v0.4
* Remove extra arguments from `ImageSequence` and split it into separate classes
* Add imageio PR with tests
* built-in pipelines for as_grey, normalize, cropping, as_rgb

**Comment by danielballan** [comment]
With a thumbs up from Casper I tagged v0.3.0 and put it on PyPI. I updated the release road map in my comment just above this comment.

Goals v0.3.1 are mainly build-related. We should aim to get that out by the end of the month, but I'm glad we finally have a recent pims tag!

**Comment by caspervdw** [comment]
The v0.4 milestones are ongoing and discussion continuous in #254, #250
