### ISSUE TITLE
Why does loading a TIFF take so long?

### ISSUE THREAD

**Issue by pavo** [soft-matter/pims#154]
To access a pixel position in the first frame of a tiff stack takes:
6.40000000001e-05  seconds using opencv
0.368312  seconds using pims

Video Length =  636
Video Frame Size =  (1080, 1280)

I don't think it has anything to do with the tiff stack length, and rather how the data is being handled. 

Is there a likely reason for this?  A temporary workaround for me is to store my TIFF stacks in a folder with frame numbers tif00001, tif00002, etc, loading them with opencv, but nice if we can find out why pims is so slow for loading tiffs. 

It may be because opencv object is  type 'numpy.ndarray' and the other object is class 'pims.frame.Frame'

**Comment by pavo** [comment]
Here is my code for reference:

im = cv2.imread(videopath, -1)
t0 = time.clock()
print "pixel value: ", str(float(im[1,2])), "\t",
print "that took:  ", time.clock() - t0, " seconds using opencv"

t0 = time.clock()
print "pixel value: ", str(float(video[0][1,2])), "\t",
print "that took:  ", time.clock() - t0, " seconds using pims"
print "Video Length = ", video.__len__()
print "Video Frame Size = ", video._im_sz


note that  [1,2] are different pixel values in opencv versus pims because the images are rotated 90 degrees counterclockwise in pims versus opencv :)

**Comment by pavo** [comment]
#open multipage tiff
img = Image.open(videopath)
img.seek(0)
t0 = time.clock()
print img.getpixel((1,2))
print "that took:  ", time.clock() - t0, " seconds using PIL"

Using PIL took 0.0002 seconds for accessing a pixel in one frame of the same TIFF stack.  Using the PIL Image.seek() function one can work with multi-page TIFFs (same as TIFF stack provided by my camera or ImageJ).

**Comment by danielballan** [comment]
Pims is loading the whole frame into memory, which is why it is slower. We
don't currently support reading in just part of a given frame, but ongoing
work on multidimensional data may eventually lead that way.

**Comment by pavo** [comment]
Got it.  Thanks!

**Comment by tacaswell** [comment]
It is also not clear to me that you are really doing apples-to-apples comparison

```python
t0 = time.clock()
im = cv2.imread(videopath, -1)
print "pixel value: ", str(float(im[1,2])), "\t",
print "that took: ", time.clock() - t0, " seconds using opencv"

t0 = time.clock()
video = pims.TiffStack(videopath)
print "pixel value: ", str(float(video[0][1,2])), "\t",
print "that took: ", time.clock() - t0, " seconds using pims"
print "Video Length = ", video.len()
print "Video Frame Size = ", video._im_sz
```

or 

```python
im = cv2.imread(videopath, -1)
t0 = time.clock()
print "pixel value: ", str(float(im[1,2])), "\t",
print "that took: ", time.clock() - t0, " seconds using opencv"


video = pims.TiffStack(videopath)
im = video[0]
t0 = time.clock()
print "pixel value: ", str(im[1,2])), "\t",
print "that took: ", time.clock() - t0, " seconds using pims"
print "Video Length = ", video.len()
print "Video Frame Size = ", video._im_sz
```

are probably fairer tests.  

pims currently does not do any clever caching (that is calling `v[0]` twice hits disk both times (modulo the filesystem out smarting you)).
