### ISSUE TITLE
ENH: Slicing-aware reader methods

### ISSUE THREAD

**Issue by nkeim** [soft-matter/pims#159]
This is an architectural issue at the intersection of #147, #153, and #158.

### The problem

Currently, pims `SliceableIterable` objects wisely forward unknown method calls to their ancestors, which allows methods to be "inherited" from the reader object that opened the file. However, those methods could take frame numbers as their arguments. For example, the Cine and (unmerged) NorpixSeq classes have methods for reading the timestamp of frame *i*. Being able to retrieve a timestamp without reading the entire image can make a large performance difference in some applications. In a similar fashion, these proprietary formats can store other (as yet unsupported) information such as voltages or event markers.

Therefore, methods like `get_time(frameno)` should be aware that they are being called via a child.

### A solution
`FramesSequence`-derived objects that want to support this feature provide the context `_use_map`, which would be used within the child `SliceableIterable` as follows (oversimplified for clarity):

```
# Call get_time() on the parent object
with self._ancestor.use_map(self.indices):
    self._ancestor.get_time(*args, **kw)
```

The reader class would then implement `get_time` as:

```
def get_time(self, frameno):
   actual_frameno = self._indexmap(frameno)
   # Return time of actual_frameno...
```

`use_map()`, `_indexmap()`, etc. would be implemented in the `FramesSequence` base class. `use_map()` could be thread-safe.

Thoughts? I'm open to more elegant solutions, or to the possibility that this is too much of a niche feature!

**Comment by nkeim** [comment]
The idea I *just* posted is not going to work, because the `SliceableIterable` does not actually forward method calls; it just uses `__getattr__`.

The way to make it work would be to let the ancestor object supply the names of methods that need this mapping functionality.

**Comment by nkeim** [comment]
To make sense of all this, I coded up the idea. You can [see the required changes here].(https://github.com/nkeim/pims/compare/seqreader...nkeim:sliced_methods?expand=1)

**Comment by danielballan** [comment]
I had not considered this use case. I like your solution. I think we should merge your changes, update Cine, and consider moving the mapping stuff into FramesSequence proper sometime later.

**Comment by caspervdw** [comment]
I think we could view this in the larger perspective of how to deal with metadata reading. Maybe a general Metadata object that collects al the get_something methods, correctly interprets the indices and also figures out the multidimensional case would be the most clear solution?

**Comment by nkeim** [comment]
Good point; metadata is very much a second-class entity in pims; i.e., it does not do for metadata what it does for images. See #153 for a related issue that needs solving.

My take on a metadata object: just as pims sequence objects present themselves as lists of ndarrays, the best paradigm for a metadata object might be a DataFrame. It's probably not worth implementing, but it does address every use case and access pattern you could imagine.

As it stands, the chief weakness and virtue of #160 is that it does not take a position on this larger architectural issue.

**Comment by danielballan** [comment]
I think an accessor attribute might serve well here.

```
v.md[5]  # returns a dict
v[5].md  # returns the same dict
v.md[:5]  # return a SliceableIterator of dicts
```

**Comment by tacaswell** [comment]
I think we want the transpose of a DataFrame (a list of dicts, not a dict of lists) to handle the meta-data.

**Comment by nkeim** [comment]
Yes, good! I guess what was bothering me is the time that might be required to assemble a full metadata dict for a frame, rather than just seeking to one location in the file to read one datum on demand. But on a modern OS with lots of RAM, doing multiple seeks within a few regions of the file is tolerable. So a list of dicts is probably the best API.

BTW, if someone wants to code this up and we like it, I'm fine with #160 being mothballed. It touched the sky.

**Comment by danielballan** [comment]
I think I hit upon a simple solution to this.

At constructor time, it is the reader's job to create the attributes. Any attributes that vary frame-by-frame can be set up as `SliceableIterable` objects themselves. Then:

```
class SliceableIterable(object):
    ...
    def __getattr__(self, key):
        # Remember this only gets called if __getattribute__ raises an
        # AttributeError. Try the ancestor object.
        attr = getattr(self._ancestor, key)
        if isinstance(attr, SliceableIterable):
            return SliceableIterable(attr, self.indices, len(self))
        else:
            return attr
```

As a demo, here's a test using letters in place of Frames.

```
def test_getattr():
    class MyList(list):
        my_attr = 'hello'
        s = SliceableIterable(list('ABCDEFGHIJ'), range(10))

    a = SliceableIterable(MyList('abcdefghij'), range(10))
    assert_letters_equal(a, list('abcdefghij'))
    assert_true(hasattr(a, 'my_attr'))
    assert_true(hasattr(a, 's'))
    assert_equal(a.my_attr, 'hello')
    with assert_raises(AttributeError):
        a[:5].nonexistent_attr

    s1 = a[::2].s
    assert_equal(list(s1), list('ACEGI'))
    s2 = a[::2][1:].s
    assert_equal(list(s2), list('CEGI'))
    s3 = a[::2][1:].s[0]
    assert_equal(s3, 'C')
```

**Comment by nkeim** [comment]
Cool! I really like it. `SliceableIterable`s all the way down.

The cherry on top would be a way to create these metadata `SliceableIterable` attributes that requires only functions to serve as `__getitem__()` and `__len__()`. As in

```python
class SomeMovieReader(FramesSequence):
    ...
    def _get_time(self, frameno):
        ...
    def __len__(self):
        ...
    times = SliceableIterable.from_functions(_get_time, __len__)
```

Not sure if the scoping works right on this one, but you get the idea.

**Comment by danielballan** [comment]
Yeah. I like that.

**Comment by caspervdw** [comment]
Can we close this after https://github.com/soft-matter/slicerator/pull/5 ? @nkeim

**Comment by nkeim** [comment]
Yup! Thanks for checking.
