### ISSUE TITLE
Trouble with Bioformats

### ISSUE THREAD

**Issue by mmdriscoll** [soft-matter/pims#161]
I am unable to get this working properly on Ubuntu 14.04.  I was able to pip install jpype, but when I try to use pims.Bioformats I get the following traceback:

```
  File "<ipython-input-7-1810b8c6c8a5>", line 1, in <module>
    images = pims.Bioformats('/home/swimmers3/Desktop/very_dense_new_large_swimmer_light.nd2')

  File "/home/swimmers3/anaconda/lib/python2.7/site-packages/pims/bioformats.py", line 328, in __init__
    jpype.startJVM(jpype.getDefaultJVMPath(), '-ea',

  File "/home/swimmers3/anaconda/lib/python2.7/site-packages/jpype/_core.py", line 114, in get_default_jvm_path
    return finder.get_jvm_path()

  File "/home/swimmers3/anaconda/lib/python2.7/site-packages/jpype/_jvmfinder.py", line 137, in get_jvm_path
    .format(self._libfile))

JVMNotFoundException: No JVM shared library file (libjvm.so) found. Try setting up the JAVA_HOME environment variable properly.
```

I assume that this is trying to tell me I am missing a Java library, but I am not sure of the easiest way to resolve this.  Interestingly, I was able to get this working on my Mac just by pip installing jpype....

**Comment by danielballan** [comment]
Did you pip install jpype1 specifically? I thought that was in our docs,
but I see it is not.

**Comment by mmdriscoll** [comment]
Yes, I did jpype1 - it does say that in the docs here:

https://github.com/soft-matter/pims

I don't know what is wrong, as it worked great on my mac....

On Thu, Jul 9, 2015 at 5:24 PM, Dan Allan <notifications@github.com> wrote:

> Did you pip install jpype1 specifically? I thought that was in our docs,
> but I see it is not.
>
> On Thu, Jul 9, 2015 at 4:01 PM Michelle Driscoll <notifications@github.com
> >
> wrote:
>
> > I am unable to get this working properly on Ubuntu 14.04. I was able to
> > pip install jpype, but when I try to use pims.Bioformats I get the
> > following traceback:
> >
> > File "", line 1, in
> > images =
> >
> pims.Bioformats('/home/swimmers3/Desktop/very_dense_new_large_swimmer_light.nd2')
> >
> > File
> >
> "/home/swimmers3/anaconda/lib/python2.7/site-packages/pims/bioformats.py",
> > line 328, in *init*
> > jpype.startJVM(jpype.getDefaultJVMPath(), '-ea',
> >
> > File
> > "/home/swimmers3/anaconda/lib/python2.7/site-packages/jpype/_core.py",
> line
> > 114, in get_default_jvm_path
> > return finder.get_jvm_path()
> >
> > File
> >
> "/home/swimmers3/anaconda/lib/python2.7/site-packages/jpype/_jvmfinder.py",
> > line 137, in get_jvm_path
> > .format(self._libfile))
> > JVMNotFoundException: No JVM shared library file (libjvm.so) found. Try
> > setting up the JAVA_HOME environment variable properly.
> >
> > I assume that this is trying to tell me I am missing a Java library, but
> I
> > am not sure of the easiest way to resolve this. Interestingly, I was able
> > to get this working on my Mac just by pip installing jpype....
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/soft-matter/pims/issues/161>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soft-matter/pims/issues/161#issuecomment-120148187>.
>



-- 
Michelle Driscoll
Center for Soft Matter Research, New York University
212.998.8428
md180@nyu.edu

**Comment by caspervdw** [comment]
Could you check the version? `jpype.__version__` should return `0.6.0`

If so, then this should really work. Possibly `jpype.getDefaultJVMPath()` returns a wrong path. Could you execute this function and check if the path exists?

A workaround might be installing the JDK (e.g. openjdk7) and setting the JAVA_HOME env variable properly. But the JVM should be included in 0.6.0, also on linux.

**Comment by mmdriscoll** [comment]
hmmm...

jpype.__version__ does indeed return 0.6.0

However, when I try jpype.getDefaultJVMPath(), I get the following
traceback:
-------------------------------------------------------------------
 jpype.getDefaultJVMPath()
Traceback (most recent call last):

  File "<ipython-input-13-4907300cce39>", line 1, in <module>
    jpype.getDefaultJVMPath()

  File
"/home/swimmers3/anaconda/lib/python2.7/site-packages/jpype/_core.py", line
114, in get_default_jvm_path
    return finder.get_jvm_path()

  File
"/home/swimmers3/anaconda/lib/python2.7/site-packages/jpype/_jvmfinder.py",
line 137, in get_jvm_path
    .format(self._libfile))

JVMNotFoundException: No JVM shared library file (libjvm.so) found. Try
setting up the JAVA_HOME environment variable properly.
--------------------------------------------------
However, the workaround uyou suggested fixed the problem.  After I
installed openJDK7, pims.Bioformats was able to read in an .nd2 file.

Thanks for the help.

On Fri, Jul 10, 2015 at 3:28 AM, Casper van der Wel <
notifications@github.com> wrote:

> Could you check the version? jpype.__version__ should return 0.6.0
>
> If so, then this should really work. Possibly jpype.getDefaultJVMPath()
> returns a wrong path. Could you execute this function and check if the path
> exists?
>
> A workaround might be installing the JDK (e.g. openjdk7) and setting the
> JAVA_HOME env variable properly. But the JVM should be included in 0.6.0,
> also on linux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soft-matter/pims/issues/161#issuecomment-120266465>.
>



-- 
Michelle Driscoll
Center for Soft Matter Research, New York University
212.998.8428
md180@nyu.edu

**Comment by danielballan** [comment]
@mmdriscoll No luck?

**Comment by caspervdw** [comment]
@mmdriscoll great that installing openJDK7 solved the problem. For the rest this seems to be a `jpype` issue, could you raise the issue at https://github.com/originell/jpype/issues ?

@danielballan , check mmdriscolls message again, there is some text between the original message citations

Closing
