### ISSUE TITLE
TIFF stacks are rotated 90° counterclockwise

### ISSUE THREAD

**Issue by luhk** [soft-matter/pims#164]
At least with the PIL and tifffile backends (I couldn't get libtiff to work), all images appear to be rotated counterclockwise by 90°. If, for instance, I split the TIFF stack into single JPEGs (using e. g. ImageJ) and load them into an ImageSequence, the images are not rotated.

I guess this weirdness has to do with all the flipping and transposing in the get_frame functions.

**Comment by tacaswell** [comment]
What is the source of your tiffs and can you put one someplace we can see it?

Is it really a rotation or is it a transpose?

**Comment by luhk** [comment]
Here is a file created by the TILL Live Acquisition software,
https://owncloud.tuwien.ac.at/public.php?service=files&t=286c732c1ba016480fddbd3e0dc3931d

I do have the same problem with files created by software based on OpenImageIO and tifffile. Apparently I am not the first one to experience this; it is also mentioned in issue #154 in the second comment at the bottom.

If I transpose the image, it is still mirrored along the vertical axis, so I'd say this is really a rotation.

**Comment by tacaswell** [comment]
What version of pims are you using?

**Comment by luhk** [comment]
Version 0.2.2
