### ISSUE TITLE
Pickling issue of FramesSequence

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#178]
When working on the trackpy walkthrough, I came across the following issue:

    from IPython import parallel
    from IPython.display import display

    client = parallel.Client()
    view = client.load_balanced_view()
    view.map_async(curried_locate, frames[:32])

Where frames is a FramesSequence. The code produces the following error:

    C:\Anaconda\lib\site-packages\IPython\kernel\zmq\serialize.pyc in serialize_object(obj,     buffer_threshold, item_threshold)
     87         buffers.extend(_extract_buffers(cobj, buffer_threshold))
     88 
    ---> 89     buffers.insert(0, pickle.dumps(cobj, PICKLE_PROTOCOL))
     90     return buffers
     91 

    PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

This is tested against the current pims master. If I rollback to 0.2.2, there is no issue. I guess this is an issue with the SlicableIterable.

**Comment by caspervdw** [comment]
We should fix this before 0.3, because it breaks parallel feature finding in trackpy.

**Comment by danielballan** [comment]
I confirmed that this works now. See soft-matter/trackpy-examples#29.
