### ISSUE TITLE
Norpix reader ndarray.tobytes gives error

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#180]
Travis caught the following exception:

	======================================================================
	ERROR: test_get_frame (pims.tests.test_norpix.test_defaults)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/travis/build/soft-matter/pims/pims/tests/test_norpix.py", line 42, in test_get_frame
		fhash = hash(np.array(fr).tobytes())
	AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'
	======================================================================
	ERROR: test_get_frame (pims.tests.test_norpix.test_dtype)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/travis/build/soft-matter/pims/pims/tests/test_norpix.py", line 42, in test_get_frame
		fhash = hash(np.array(fr).tobytes())
	AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'
	======================================================================
	ERROR: test_get_frame (pims.tests.test_norpix.test_process_func)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/travis/build/soft-matter/pims/pims/tests/test_norpix.py", line 42, in test_get_frame
		fhash = hash(np.array(fr).tobytes())
	AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'

**Comment by danielballan** [comment]
`tobytes` is numpy 1.9 only

**Comment by caspervdw** [comment]
Then why did it ever pass? :confused:

**Comment by caspervdw** [comment]
@nkeim, do you have time to look into this?

**Comment by nkeim** [comment]
Yikes! Of course. Sorry I don't follow activity on this repo. It looks like I can just replace `tobytes` with `tostring`. Expect a PR.

**Comment by nkeim** [comment]
The failing environments start out with numpy *1.9.2* — pims doesn't have any legacy environments. But somehow `conda install -n testenv -c soft-matter --yes pyav tifffile` causes numpy to be downgraded to 1.8.2. That does *not* happen when I attempt to reproduce the Python 2 build environment on my Mac. So, it's weird. But I just created #181 .

**Comment by danielballan** [comment]
There may not be a PyAV build for numpy 1.9.2. Since that has C in it, it pins the numpy version. I'll open another issue and check later.
