### ISSUE TITLE
Bio-formats time/series timestamp metadata mixup?

### ISSUE THREAD

**Issue by stevendbrown** [soft-matter/pims#187]
I've installed pims and the jar file for bioformats to read nd2 files. I can successfully open the nd2 and access the data therein, but I'm wondering if the t_s metadata is being mixed up somewhere. With `test` holding the return value of `pims.open()`, `test.default_coords == {u'c': 0, u't': 0}`, `test.bundle_axes == [u'y', u'x']`, `test.iter_axes == [u't']`, `test.series == 0`, and `test.size_series == 27`, I run the following code in iPython notebook to get the DeltaT for each image in the time series:
```python
t_s = []
for t_index in range(0, 100):
    t_s.append(test[t_index].metadata["t_s"])
```
However, the resulting t_s contains the following delta values, which is certainly too fast for what actually happened in the ND2 and has a pause every 27 images, suggesting that the series/plane indices are "flipped" in the timeseries interpretation:
```
[0.9219700636267663,
 1.9037450135946274,
 3.0288364636301996,
 3.95556303858757,
 4.868468838632107,
 5.9362832885980605,
 6.8355563386082645,
 7.827144663631916,
 9.475698738574982,
 10.656013988614083,
 11.653529838621616,
 12.668974513590335,
 13.80917391359806,
 14.803709763586522,
 15.842455963611602,
 16.894236913621427,
 18.006129413604736,
 19.104716288626193,
 20.13068478858471,
 21.167891713619234,
 22.123279888629913,
 23.425835913598537,
 24.38865488862991,
 25.379765988588332,
 26.335722938597204,
 27.349123038589955,
 28.729651288628578,
 60.8162427136302,
 61.46171876358986,
 62.1168248385787,
 62.87410923862457,
 63.655140763580796,
 64.27967733860015,
 64.84931998860836,
 65.45493756359815,
 66.06824346357584,
 66.6852229385972,
 67.31949451363087,
 67.98029468858242,
 68.71559001362324,
 69.374028588593,
 70.02721916359663,
 70.73407038861514,
 71.42024456357956,
 72.31681051361561,
 73.107865688622,
 73.74822493863105,
 74.37522806358338,
 74.97352471357584,
 75.87358053863049,
 76.53868406361342,
 77.42659081357718,
 78.12829901361465,
 79.1507378885746,
 120.96144261360169,
 121.99119918859004,
 123.02214441359042,
 124.00523436361551,
 125.23334946358204,
 126.18084891360998,
 127.14750571358204,
 128.29976698857547,
 129.5479872136116,
 130.77767661362887,
 131.89068833857775,
 133.1268966885805,
 134.13226691359282,
 135.29994918859006,
 136.3480593636036,
 137.45545488858224,
 138.45935091358425,
 139.71330966359378,
 140.73377966362239,
 141.84502403861285,
 142.83436748862266,
 143.79208716362714,
 144.79577266359328,
 145.92105828857422,
 146.87656981360914,
 147.89340736359358,
 149.2373079636097,
 181.21744368863105,
 182.08611658859252,
 182.87250106358528,
 183.5572058135867,
 184.37544556361436,
 185.0481586636305,
 185.94679756361245,
 186.62292186361552,
 187.60025431358815,
 188.35336656361818,
 189.12251141357422,
 189.83873028862476,
 190.55731078863144,
 191.34162231361867,
 192.0975947136283,
 192.86485026359557,
 193.6300066385865,
 194.45286463862658,
 195.28603488862515]
```
I couldn't find a place in the pims code where this would be happening - if this is just a Bio-formats issue rather than a pims issue, so be it. However, if you happen to know how I could workaround the problem for now I'd be grateful to know it.

**Comment by caspervdw** [comment]
This appears to me as a bioformats issue. Bioformats recognizes the image shape and sorts out the axes. As it appears, you have a CTYX image. The 'series' axis is meant for images that consists of multiple measurements, for instant at different positions or even with different techniques. You have size 27 separate measurements in your file.

I had these issues before with CTZYX .nd2 images, T and Z dimensions are flipped or put into the series channel. This was solved in a later bioformats version. Do you use the default version that is automatically downloaded by pims?

You might want to try out https://github.com/soft-matter/pims_nd2 , this circumvents bioformats.

**Comment by stevendbrown** [comment]
I'm using the most recent loci_tools.jar from the Bioformats website.

Thanks for the tip! `pims_nd2` mostly worked with the current release of the ND2SDK by just pointing `ND2SK.py` to the right ND2SDK library file and disabling the host checks. `dTimeStart` is not returning a value besides 0.0 so I cannot yet calibrate between .nd2 files; other `c_double` values (e.g. `dCalibration`) seem fine.

**Comment by caspervdw** [comment]
Good that pims_nd2 works for you. Do you mean it's working on linux? If you have time could you make a PR with your changes and an issue about the dTimeStart? Then we can discuss further there. Closing here as this is no pims issue.
