### ISSUE TITLE
open class finder does not work completely

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#205]
I tried to open an nd2 file using `pims.open`, but then I get:

    UnknownFormatError: Could not autodetect how to load a file of type nd2. Try manually specifying a  loader class, e.g. Video(dummyfilename.nd2)

While `pims.ND2_Reader(...)` works just fine and `pims.Bioformats(...)` too. Both define the `class_exts` method, and it they contain `'.nd2'`.

Any thoughts on this?

**Comment by danielballan** [comment]
[This line](https://github.com/soft-matter/pims/blob/master/pims/api.py#L139) needs to be updated to search for subclasses of `FramesSequenceND` as well.

**Comment by caspervdw** [comment]
That is a fast response! That figures. This should go into 0.3.3.

**Comment by caspervdw** [comment]
Closing via #207
