### ISSUE TITLE
Feature request: Norpix color images

### ISSUE THREAD

**Issue by dmopalmer** [soft-matter/pims#215]
Currently, Norpix .seq files don't support color camera files.  Multi-color camera files raise:
```
Only uncompressed mono images are supported in .seq files
```

**Comment by nkeim** [comment]
Thank you! That must be a frustrating error to receive. As I recall, the `seq` format does not actually store color data, but instead simply encodes the color filter pattern. pims will have to use a color reconstruction algorithm to properly read these files. OpenCV appears to include the appropriate algorithm(s) for the bayer pattern.

This is a pretty low priority for me, but someone else (or you) may wish to take the initiative. One thing that would help is if you could attach here a very small (just 1 or 2 frames, low resolution) color sample file.

**Comment by caspervdw** [comment]
Closing because it is fixed in #218
