### ISSUE TITLE
Is PyAv switching the image axes?

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#234]
While writing the tests for #233, I saw that the order of axes in the test movie might be reversed (see https://github.com/soft-matter/pims/pull/233/files#diff-a91a5c03fe05e2269252147fc26227a4R440).

Could someone who actually has PyAv installed check if images are really read in (x, y) axes order instead of (y, x)?

And should we fix this?

**Comment by caspervdw** [comment]
Anybody?

**Comment by danielballan** [comment]
My local FFmpeg config is screwy. I made a note to revisit. Sorry for letting this sit so long.

**Comment by caspervdw** [comment]
Closing through #251
