### ISSUE TITLE
How can I create new a frame sequence from another.

### ISSUE THREAD

**Issue by rraadd88** [soft-matter/pims#236]
I have a frames object with shape (121,5,512,512).
From that, I need to sum the 5 z stacks and create a new frames object with shape (121,512,512).
I am trying this,
```
for i in range(len(frames)):
    new_frames[i]=frames[i][0]+frames[i][1]+frames[i][2]+frames[i][3]+frames[i][4]
```
>>NameError: name 'new_frames' is not defined

How can I define new_frames as a frames object?
Is there any other way to do it?
Thanks.

**Comment by caspervdw** [comment]
Hi @rraadd88, I see you are using a reader that provides 3d frames. The thing with FramesSequence objects is, that they dont't actiLl

**Comment by caspervdw** [comment]
Hi @rraadd88, I see you are using a reader that provides 3d frames. The thing with FramesSequence objects is, that they don't actually contain the image data (that would give memory issues), but only references where to read it on the hard drive.

So what you want is a so-called `pipeline`, which is rather new in pims and still undocumented. You'll need pims 0.3.3 and define a function:

    import pims
    @pims.pipeline
    def average_z(image):
        return image.sum(axis=0)  # the same as image[0] + ... + image[4]

This function is 'decorated' with a pims pipeline, which makes it recognize FramesSequence objects. If you then apply it to your `frames` object, it will create a new FramesSequence that holds reference to the older via the pipeline. Like this:

    new_frames = average_z(frames)
    new_frames[0]  # print the first frame of shape (512, 512)

**Comment by tacaswell** [comment]
This is small enough I would just do

```
new_seq = np.asarray([np.sum(fr, axis=0) for fr in frames])
```

**Comment by rraadd88** [comment]
@caspervdw , @tacaswell, 
both work very well.
Thanks a lot for the help.
both pims and trackpy are excellent projects.

**Comment by tacaswell** [comment]
Your welcome! Glad these projects are being used!
