### ISSUE TITLE
Imagesequence suddenly reads 16-bit

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#237]
I have 8-bit images that are suddenly read in as 16-bit by skimage (0.11.3). This is probably an issue (or general API?) in skimage, but it is annoying for reproducability of my tracking.

**Comment by danielballan** [comment]
Hrm. If there is a switch in skimage to go back to old behavior, we should expose it. But my advice for reproducibility is to stash a conda env YAML pinning an old version of skimage. I found I could never keep up with tiny semi-breaking changes like this. I just pin to a set of deps for the lifetime of a project, updating selectively if I need some particular new thing.

**Comment by caspervdw** [comment]
Closing as this is an skimage issue.
