### ISSUE TITLE
3d stack play ValueError

### ISSUE THREAD

**Issue by zoeith** [soft-matter/pims#238]
While trying out pims `play` function in a notebook I got this error:
`ValueError: unknown encoding codec: 'libvpx'`

I know that this has something to do with my install of ffmpeg (2.2.4 on Ubuntu 12.04) but I can't figure out how to fix the weird dependency tangle. I found this: https://github.com/mikeboers/PyAV/issues/57 but even the recipe by @mkassner didn't fix this. I also tried some of the recipes here: https://github.com/conda-forge/staged-recipes/issues/708

This test https://github.com/soft-matter/pims/pull/71 worked?

**Comment by zoeith** [comment]
@danielballan, I looked into this a bit more. The `build.sh` files in the [recipes](https://anaconda.org/soft-matter/ffmpeg/files) don't have `--enable-libvpx` in the configure list.

Should their be repositories for all the soft-matter recipes?

**Comment by danielballan** [comment]
I built the soft-matter conda packages before conda-forge existed. Now that conda-forge is shipping ffmpeg and its dependencies, let's plan to drop my recipe and focus on getting conda-forge's recipe right.

https://github.com/conda-forge/ffmpeg-feedstock

Their recipe is missing libvpx too. Any interest in opening a PR over there to add the needed flag? I have commit rights on that repo.

**Comment by zoeith** [comment]
Sounds good, will do.

**Comment by zoeith** [comment]
Welp, that didn't get far... see https://github.com/conda-forge/ffmpeg-feedstock/issues/8

**Comment by zoeith** [comment]
I think this is an important feature of pims especially for bringing matlab and IDL users to python, but also for checking tracking results and viewing/sharing data. However, I've found building this to be a serious can of worms... see, for example, https://github.com/conda-forge/staged-recipes/pull/1040 is just the first of the 3 (at least) dependencies for ffmpeg with libvpx, and I can't seem to get that to build.

**Comment by danielballan** [comment]
It's a real challenge. I spent a lot of time getting this working awhile back. I'll revisit and try to get some help from the heroes over at conda-forge.

**Comment by caspervdw** [comment]
@zoeith  In the meantime, maybe the solution via ImageIO or MoviePy works for you? see PR #233 .  They use pipes instead of the direct interface that PyAv uses.

**Comment by caspervdw** [comment]
In the meantime, PyAv is now supported by conda-forge. Closing
