### ISSUE TITLE
Conda install downgrades numpy to 1.9

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#240]
When installing PIMS 0.3.3 over conda (Win64):

```
conda install pims -c soft-matter
```

Conda wants to downgrade many packages, especially numpy goes to 1.9:

```
The following packages will be DOWNGRADED due to dependency conflicts:

matplotlib:   1.5.1-np111py34_0              --> 1.4.3-np19py34_1
numexpr:      2.6.0-np111py34_0              --> 2.4.4-np19py34_0
numpy:        1.11.1-py34_1                  --> 1.9.3-py34_3
scikit-image: 0.12.3-np111py34_1             --> 0.11.3-np19py34_0
scikit-learn: 0.17.1-np111py34_1             --> 0.16.1-np19py34_0
scipy:        0.17.1-np111py34_0             --> 0.16.0-np19py34_0
```

I really don't know anything about the conda-magic. @danielballan do you have a clue how to fix this?

**Comment by tacaswell** [comment]
We need to rebuild pims with a new version of numpy.  The conflict is probably caused by `tifffile`? Try adding the `conda-forge` channel?

**Comment by danielballan** [comment]
Gotta move to conda-forge in general. That's probably a two-day job.

**Comment by caspervdw** [comment]
Tifffile is on conda-forge indeed. It seems pretty straightforward to move our builds to conda-forge (as long as there is no compiling involved). I started with slicerator [over here](https://github.com/caspervdw/staged-recipes). Are you OK with creating the PR (which would test the build)? @tacaswell @nkeim @danielballan do you want to be maintainers?

**Comment by tacaswell** [comment]
You can add me

**Comment by caspervdw** [comment]
https://github.com/conda-forge/staged-recipes/pull/1688 . If it's merged I'll proceed with pims.

**Comment by caspervdw** [comment]
Ok for some reason I entirely missed this:

https://github.com/conda-forge/staged-recipes/pull/665

It's apparently already on

**Comment by caspervdw** [comment]
@ericdill  Thanks for putting pims and slicerator on conda-forge! I proceeded with the trackpy recipe conda-forge/staged-recipes#1690

**Comment by caspervdw** [comment]
It's all online now. I am :+1: on moving fully from the soft-matter channel to conda-forge, also adapting the installation instructions and release checklist.

- tifffile, fftw, pyfftw are on conda-forge
- ffmpeg with x264 is also present (not Win)
- only thing left: PyAv. Should be doable, except for windows

**Comment by danielballan** [comment]
Sounds good. I'll try to get to PyAV this week, but if I don't manage, let's update the docs anyway. PyAV shouldn't hold this up.

Also, for legacy users who might not re-read the installation docs, we should mirror these packages to soft-matter for awhile using `anaconda copy`.

**Comment by tacaswell** [comment]
`anaconada copy` is back?

**Comment by caspervdw** [comment]
Ok I'll fix the docs somewhere this weeks.

Do we want to keep forks of the `<package>-feedstock` repo's in softmatter? I forked `pims-feedstock` already. You need a fork to do the PR for a new release.

**Comment by danielballan** [comment]
Yes, I think an org fork is a good idea.

**Comment by caspervdw** [comment]
Closing through #245
