### ISSUE TITLE
Plot_to_frame incompatible with mpl >= 1.5

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#244]
The use of `plot_to_frame` with matplotlib 1.5.1 and 1.5.3:

```
    pims.plot_to_frame(plt.figure())
```

Produces the following error:

```
    635 
    636     buf.seek(0)
--> 637     image = np.fromstring(buf.read(), dtype='uint8').reshape(*buf_shape)
    638     if close_fig:
    639         plt.close(fig)

ValueError: total size of new array must be unchanged
```

It seems that the figure shape is behaving differently than on 1.4.3 (on which the  issue is not present)

**Comment by tacaswell** [comment]
Do you have `rcParms['savefig.bbox'] == 'tight'` ?

What are the reported shapes?

I can not reproduce this.

**Comment by caspervdw** [comment]
Spot on, indeed the tight bbox was the cause. Apparently I did not have the same set of rc settings for the different mpl versions.

We need a fix to solve this use case:
```
import pims
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rcParams.update({'savefig.bbox': 'tight'})
pims.plot_to_frame(plt.figure())
```

**Comment by danielballan** [comment]
Hmm. Is the right approach to check the contents of rcParams inside our function and just fail more informatively?

**Comment by tacaswell** [comment]
Instead of to the raw RGBA buffer, write it as a png to the bytes array and then read the png.

It is a bit more work (as we have the extra encode/decode step), but it takes care of the size meta-data being properly propagated.

**Comment by caspervdw** [comment]
That sounds reasonable, we just need a check to test the performance overhead.

**Comment by tacaswell** [comment]
png encoding is the method we use in webagg/nbagg so I am not be super worried about that.
