### ISSUE TITLE
problems with .lif files

### ISSUE THREAD

**Issue by mmdriscoll** [soft-matter/pims#260]
Leica's software has the dumb habit of saving multiple stacks (i.e. "experiments") as one giant .lif file.  I can use Bioformats to read in a .lif file, but I can only "see" the first stack.  In other words, I get a pims object that only contains the data in the first "experiment".  When I import this using bioformats in ImageJ, I get a pop-up asking me to chose which experiment(s) to import - is there a some equivalent to this in pims?  i.e., is there an option to specify which of the stacks in the .lif file I want?

**Comment by caspervdw** [comment]
Hi @mmdriscoll, although I have never worked with .lif files, I believe you can change this with the `series` property or argument:

```
    reader = Bioformats(filename, series=2)
```
Or

```
    reader.series = 2
```

**Comment by mmdriscoll** [comment]
@caspervdw Thanks, this totally solved my problem - I should have taken a peak at the code.  Next time you update the documentation, consider adding a reference to this.

**Comment by caspervdw** [comment]
I will insert it during the v0.4 release! Thanks.
