### ISSUE TITLE
pyqt4 and pims

### ISSUE THREAD

**Issue by seghier** [soft-matter/pims#275]
hello ; i want create image sequence viewer but the documentation don't give detailed examples .
from pims import ImageSequence
images = ImageSequence('img-*.png')
images 
how  i can load a folder and play the sequence ? is there any simple examples how to do that ?

**Comment by nkeim** [comment]
Hi! Currently the best way to do that is [pimsviewer](https://github.com/soft-matter/pimsviewer). It is still under development but you should try it. It will allow you to play the sequence that you loaded in the example you gave.

You could also look at ImageJ, which is very mature and has many, many features. That is not written in Python and is not based on pims.

**Comment by tacaswell** [comment]
Closing as out of scope for pims.
