### ISSUE TITLE
metaclass conflict

### ISSUE THREAD

**Issue by ericthred** [soft-matter/pims#276]
Hello, I've recently started using both pims and trackpy, and love them both. Recently, however, I updated my anaconda environment, and now I get a metaclass conflict whenever I try to import pims. I started with a fresh environment (python 2.7), installing pims from scratch, but I get the same error. uninstalling pims 0.4 and trying again with 0.3.3 does not solve the issue. Can't use either pims or trackpy until I figure this out. Any help would be appreciated.

Error:

In [1]: import pims
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-c035db68c7c1> in <module>()
----> 1 import pims

/Users/ericthred/anaconda3/envs/py2_image/lib/python2.7/site-packages/pims/__init__.py in <module>()
----> 1 from pims.api import *
      2 
      3 from ._version import get_versions
      4 __version__ = get_versions()['version']
      5 del get_versions

/Users/ericthred/anaconda3/envs/py2_image/lib/python2.7/site-packages/pims/api.py in <module>()
      3 
      4 from slicerator import pipeline
----> 5 from pims.base_frames import FramesSequence, FramesSequenceND
      6 from pims.frame import Frame
      7 from pims.display import (export, play, scrollable_stack, to_rgb, normalize,

/Users/ericthred/anaconda3/envs/py2_image/lib/python2.7/site-packages/pims/base_frames.py in <module>()
     14 
     15 
---> 16 class FramesStream(with_metaclass(ABCMeta, object)):
     17     """
     18     A base class for wrapping input data which knows how to

/Users/ericthred/anaconda3/envs/py2_image/lib/python2.7/abc.pyc in __new__(mcls, name, bases, namespace)
     85 
     86     def __new__(mcls, name, bases, namespace):
---> 87         cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
     88         # Compute set of abstract method names
     89         abstracts = set(name

TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by tacaswell** [comment]
Does it work with python3?

**Comment by tacaswell** [comment]
This looks like this is a bug (?) is six 1.10.  Downgrading to six==1.9 fixes the import.

**Comment by tacaswell** [comment]
https://github.com/benjaminp/six/issues/210 and points to the correct fix, we are using both `with_metaclass` and `__metaclass__`, you only need one of them.

**Comment by danielballan** [comment]
Thanks for flagging this @ericthred. I'll push a bugfix release of pims to PyPI shortly.

**Comment by ericthred** [comment]
Awesome, such a fast reply. Thanks for fixing it! Looking forward to getting pims working again.

**Comment by jakirkham** [comment]
Just ran into this issue recently and was about to open an issue when I found you already fixed it. 🎉 Any thoughts on doing a patch release with this change?
