### ISSUE TITLE
Out-of-core processing

### ISSUE THREAD

**Issue by outlace** [soft-matter/pims#278]
It seems like PIMS can do lazy-loading of a single frame of a video/multi-stack image, but I just want to be clear. I want to be able to process large video several frames at a time since they're too big to fit in memory and because I'm using ipyparallel to operate on different set of frames in parallel. Does PIMS do that?

**Comment by caspervdw** [comment]
Hi @outlace, yes, PIMS has recently started to support lazy processing of videos using the package `slicerator`: see [here](http://soft-matter.github.io/pims/dev/pipelines.html). Parallel processing using this pipeline architecture is defenitely on the wish list, but as far as I know nobody really looked at this yet. Maybe @nkeim knows more?

Related: https://github.com/soft-matter/slicerator/issues/22

**Comment by nkeim** [comment]
Hi @outlace! I don't know much more; I have a lot of movies so I assign each worker to analyze an entire movie. 

I'm not sure I understand your application. It sounds like you are already using your ipyparallel cluster for something else and want to load frames in the main process?

One option is to start a 2nd ipyparallel cluster...

One strategy that's worked for me in a similar situation: run `pims.open` in all of your workers and assign the reader object to a global variable in each worker. Then when you call `LoadBalancedView.imap()` or whatever you can just pass in a sequence of frame numbers; your mapping function will use the pims reader already defined on each worker. Does that make sense for your application?

**Comment by outlace** [comment]
I'm trying to process a different subset of frames from the same movie in different processes, such that each process only loads it's subset of frames (because the full movie may be larger than RAM). Sounds like what you described would work

**Comment by nkeim** [comment]
Great! I'm closing this for now but feel free to post follow-up.
