### ISSUE TITLE
Inconsistent behavior between source 0.4.1 and PyPI 0.4.1

### ISSUE THREAD

**Issue by charlesreid1** [soft-matter/pims#282]
I believe there is an issue with the version of pims (nominally 0.4.1) available through PyPI and installed via `pip install pims`. Specifically, the behavior relates to the `as_grey` parameter in the `ImageSequence` class, which was removed in [this pims commit](https://github.com/soft-matter/pims/commit/f97634337afccc8be01d10f35c4165d2bbca011b#diff-00de0855a42a33014c23a4ba27e397d9) back in January 2017.

The [pims in PyPI](https://pypi.python.org/pypi/PIMS) lists the latest release as 0.4.1, which was [released in September](https://github.com/soft-matter/pims/releases). (This is the pims I was using to regenerate the notebooks.) This version *should* have had the `as_grey` parameter removed, since the commit that removed it was made back in January, but the pims installed from PyPI (via `pip install pims`) does not remove the `as_grey` parameter. Building pims direct from source does remove the `as_grey` parameter and raises an exception if the parameter is used.

I made [a gist](https://gist.github.com/charlesreid1/f37b5c5761fa1a5c89cbde17ffcdeaef) that illustrates what's going on - it includes commands to set up a Docker container, build pims, and load a simple pims ImageSequence using the `as_grey` parameter under two separate scenarios: using pims from source, and using pims from PyPI. This uses the standard [travis-garnet](https://hub.docker.com/r/travisci/ci-garnet/tags/) image from Dockerhub, and runs some commands taken almost verbatim from the .travis.yml file in the pims repo. You can see that installing pims from source leads to an error when using the `as_grey` parameter, but installing pims via pip does not. 

I believe what's happening is an older, pre-January 2017 version of pims was bundled and submitted to PyPI under the moniker of 0.4.1. (The version string is 0.4.1 in both cases, although the behavior is definitely different.)

**Comment by nkeim** [comment]
Yes, this is confusing! [v0.4.1](https://github.com/soft-matter/pims/releases/tag/v0.4.1) was a hotfix release to address a critical issue with a dependency. @danielballan used a [separate branch](https://github.com/soft-matter/pims/tree/v0.4.x) to produce that release.

I don't know what are the current plans for a v0.5 release. The [issues marked for that milestone](https://github.com/soft-matter/pims/milestone/8) are all very old. Do the pims core contributors have any thoughts about what is left to be done?

**Comment by tacaswell** [comment]
The commit removing `as_grey` is on the master branch and not on the branch used for 0.4.1 as @nkeim said.  This was very intentional, following the spirit of semantic versioning we should not change behavior in a bug-fix release!

How are you checking the version of the source installed pims?  If I install from master branch I get:

```python
In [2]: import pims

In [3]: pims.__version__
Out[3]: '0.4+30.g9cb60ce'
```
