### ISSUE TITLE
Multipage TIFFs load incorrectly with recent tifffile

### ISSUE THREAD

**Issue by jakirkham** [soft-matter/pims#286]
This is not so much a `pims` bug as a `tifffile` bug. However it would be worthwhile to look into a workaround at the `pims` level in the interim. Namely `tifffile` misreports the number of page in a multipage TIFF when inspecting the `series`. ( https://github.com/blink1073/tifffile/issues/34 )

**Comment by caspervdw** [comment]
Thanks @jakirkham for the report. As you probably noticed, we are hands short for this project and I also have no time to look into this currently.
Probably this is related to the currently failing tests https://travis-ci.org/soft-matter/pims/builds/331783459

**Comment by jakirkham** [comment]
Sorry for not updating. This should be fixed in this tifffile 0.14.0. IOW this can be closed.
