### ISSUE TITLE
imread() got an unexpected keyword argument 'plugin'

### ISSUE THREAD

**Issue by swarnak25** [soft-matter/pims#289]
I have updated the packages.I don't know what else to do?
frames = pims.ImageSequence ('C:\\'r'Users\swarnak\TrackingWithPython\trackpy-examples-master\sample_data\bulk_water\*.png', as_grey=True)
Traceback (most recent call last):

  File "<ipython-input-13-6f292a3747c3>", line 1, in <module>
    frames = pims.ImageSequence ('C:\\'r'Users\swarnak\TrackingWithPython\trackpy-examples-master\sample_data\bulk_water\*.png', as_grey=True)

  File "C:\Users\swarnak\Anaconda3a\lib\site-packages\pims\image_sequence.py", line 97, in __init__
    tmp = self.imread(self._filepaths[0], **self.kwargs)

  File "C:\Users\swarnak\Anaconda3a\lib\site-packages\pims\image_sequence.py", line 125, in imread
    return imread(filename, **kwargs)

  File "C:\Users\swarnak\Anaconda3a\lib\site-packages\matplotlib\pyplot.py", line 2381, in imread
    return _imread(*args, **kwargs)

TypeError: imread() got an unexpected keyword argument 'plugin'

**Comment by swarnak25** [comment]
I forgot to update trackpy. Probably updating trackpy has fixed it.

**Comment by caspervdw** [comment]
Great, please let us know if you have more questions

**Comment by Burak2175** [comment]
I still have the same problem. I am using the most current version of libraries.  How can ı fix. error message here.
TypeError: imread() got an unexpected keyword argument 'plugin'

**Comment by caspervdw** [comment]
Hi, thanks for the report. Is the error traceback the same? Could you post it again to be sure, along with relevant versions (python, pims, matplotlib, scipy)?

**Comment by Burak2175** [comment]
The PIMS library appeared in the most recent version. But the problem was improved by updating the scikit-learn library. Many thanks for your interest.

**Comment by caspervdw** [comment]
So your issue is solved?

**Comment by Burak2175** [comment]
Yes, issue solved. thank you so much.

**Comment by SimonStuij** [comment]
Though my issue is solved this is maybe good to be aware of:
After reinstalling trackpy and pims using the current latest versions on conda-forge (tp 0.4.2) and pims 0.4.1 I received exactly the same error metnioned above while trying to load a tiff imagesequence:
_imread() got an unexpected keyword argument 'plugin'_

My dependency versions: ('scipy', '1.4.1'),('matplotlib', '3.2.1'),('skimage', '0.16.2'),('python', '3.7.6')

However, after installing the version that is on the current master branch the error disappeared and loading working fine. Could this possibly be related to issue #282  where also problems with version 0.4.1  are mentioned
