### ISSUE TITLE
convert color movies to 8-bit for pims.Video?

### ISSUE THREAD

**Issue by mmdriscoll** [soft-matter/pims#290]
I am trying to use trackpy for locating in RGB video images.  At the moment I have written a wrapper to convert the video, using skimage.color.rgb2gray() for each pims image, and then I do my processing.  I am wondering if there is a better way to do this, e.g. a pims way to deal with color video images.  

pims.ImageSequence has the option 'as_gray', but this does not seem to be a choice for other image types.  Alternatively, there is the process_func argument where I could write my conversion, but again this seems to be only for ImageSequence.

Am I missing something obvious?

**Comment by nkeim** [comment]
Yes, you are missing something that would be totally obvious except that it’s not documented :). The “pipeline” feature lets you define an arbitrary function to process your images on demand. See https://github.com/soft-matter/pims/issues/236#issuecomment-218885653

On Apr 2, 2018, 5:29 PM -0700, Michelle Driscoll <notifications@github.com>, wrote:

I am trying to use trackpy for locating in RGB video images. At the moment I have written a wrapper to convert the video, using skimage.color.rgb2gray() for each pims image, and then I do my processing. I am wondering if there is a better way to do this, e.g. a pims way to deal with color video images.

pims.ImageSequence has the option 'as_gray', but this does not seem to be a choice for other image types. Alternatively, there is the process_func argument where I could write my conversion, but again this seems to be only for ImageSequence.

Am I missing something obvious?
