### ISSUE TITLE
metaclass conflict w/ pims & trackpy

### ISSUE THREAD

**Issue by colmkel** [soft-matter/pims#291]
Hi - I've been trying to install trackpy v0.3.0 by following the instructions [here](http://soft-matter.github.io/trackpy/v0.3.0/installation.html). When I try to load pims in a Jupyter notebook following [this walkthrough](http://soft-matter.github.io/trackpy/v0.3.0/tutorial/walkthrough.html), I get an error (see below). I have installed both trackpy and pims both from the terminal and [from the Jupyter notebook itself](https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/). Following some of the advice on [this thread](https://github.com/soft-matter/pims/issues/276), I downgraded the six package to 1.9 (I also tried 1.10), but that didn't help.

Any help would be much appreciated!

Error: 
import pims
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-c035db68c7c1> in <module>()
----> 1 import pims

/anaconda3/lib/python2.7/site-packages/pims/__init__.py in <module>()
----> 1 from pims.api import *
      2 
      3 from ._version import get_versions
      4 __version__ = get_versions()['version']
      5 del get_versions

/anaconda3/lib/python2.7/site-packages/pims/api.py in <module>()
      2                         unicode_literals)
      3 
----> 4 from pims.base_frames import FramesSequence
      5 from pims.frame import Frame
      6 from pims.export import export, play

/anaconda3/lib/python2.7/site-packages/pims/base_frames.py in <module>()
     13 
     14 
---> 15 class FramesStream(with_metaclass(ABCMeta, object)):
     16     """
     17     A base class for wrapping input data which knows how to

/anaconda3/lib/python2.7/abc.pyc in __new__(mcls, name, bases, namespace)
     85 
     86     def __new__(mcls, name, bases, namespace):
---> 87         cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
     88         # Compute set of abstract method names
     89         abstracts = set(name

TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by nkeim** [comment]
Hi! Are you trying to install trackpy v0.3.0 because you need to reproduce a result exactly? I ask because v0.4.1 (or, at least, v0.3.2) is compatible with a wider range of package versions. You may be able to then use a version of pims that works in your environment.

That said, what version of pims is this? How are you installing it?

**Comment by nkeim** [comment]
Oh dear! My DuckDuckGo search for "installing trackpy" also brings up the v0.3.0 page from 2015. I'm not sure how we could fix that, except to edit/remove the page directly. Fellow contributors: any ideas?

You need to make sure the Python executable(s) you are using are from the same environment that you installed trackpy in. In this case, that would be `/anaconda3/bin/python`, `/anaconda3/bin/ipython`, `/anaconda3/bin/jupyter`, etc. That looks to be the cause of your problem.

If you are using the Terminal, running `source /anaconda3/bin/activate base` will fix this for the duration of your session. You can also use the Launcher (a GUI app installed by Anaconda). Obviously there are other (and more permanent) ways to make sure you are not using the Mac's python version.

**Comment by colmkel** [comment]
So I tried running 

source /anaconda3/bin/activate base 

in the terminal window before launching the Jupyter notebook, but that doesn't seem to help. Can you point me to a source telling me how to check and ensure that the Python executable(s) I'm using are from the same environment that I installed trackpy in?

Thanks again!

**Comment by nkeim** [comment]
Weird. I don't actually know of a good resource offhand. But something pertinent to your situation would be to try

```python
import numpy
print(numpy.__file__)
```

which of course should report a path in `/anaconda/lib`.

You may have a `PYTHONPATH` or other environment variable set that is compelling Anaconda python to use packages in a different installation.

**Comment by colmkel** [comment]
When I run those commands, I get

/anaconda3/lib/python2.7/site-packages/numpy/__init__.pyc

**Comment by colmkel** [comment]
OK, I uninstalled anaconda and reinstalled it, and that seems to have fixed everything. It's possible that I accidentally installed the python 2.7 version of anaconda the first time around.

**Comment by nkeim** [comment]
Weird—conda is supposed to stop things like that. Thanks for your patience!
