### ISSUE TITLE
DOC: Document pipelines

### ISSUE THREAD

**Issue by nkeim** [soft-matter/pims#293]
We need a page in the documentation to show how pipelines can be used to filter images, convert color to grayscale, etc.

Here is an existing example: https://github.com/soft-matter/pims/issues/236#issuecomment-218885653

This need keeps coming up:
- https://github.com/soft-matter/pims/issues/236#issuecomment-218885653
- #290 
- #292 

We get pipelines from [slicerator](https://github.com/soft-matter/slicerator/blob/34404e5c57008175f620754a69f1d8e26dee8b48/slicerator/__init__.py#L364), but pims needs examples for image processing.

**Comment by nkeim** [comment]
Turns out @caspervdw already wrote the docs a year ago: https://github.com/soft-matter/pims/blob/master/doc/source/pipelines.rst

Why isn't it showing up at http://soft-matter.github.io/pims/v0.4/index.html ? I am clearly ignorant of something basic.

**Comment by caspervdw** [comment]
They are accessible via http://soft-matter.github.io/pims/dev/index.html . I guess we didn’t release after we merged the pipeline docs?

**Comment by caspervdw** [comment]
@nkeim  Yep that is the issue, I checked. We could release v0.4.2 to fix this, or link to the dev docs for the time being?
