### ISSUE TITLE
Loading images from URLs

### ISSUE THREAD

**Issue by jakirkham** [soft-matter/pims#295]
Would be nice to have the option to load remote images via URL. Not totally sure how this would work, but happy to hear thoughts. :)

**Comment by caspervdw** [comment]
I agree but this is a big request ;) Maybe some more imageio integration would help us

**Comment by jakirkham** [comment]
Going to close in favor of the newer issue ( https://github.com/soft-matter/pims/issues/310 ), which has more recent discussion.
