### ISSUE TITLE
PyAVReaderTimed compatibility with PyAV 0.4

### ISSUE THREAD

**Issue by alex-amvdor** [soft-matter/pims#296]
Hello,
I am attempting to use trackpy to analyze a .avi video, and as such I need pims.Video to use the video. However, when I attempt to use it, I get an error message that I can't seem to figure out, and it doesn't seem like anyone else on the internet is getting this error message either. 

Here is the code I am running:
`v = pims.Video('C:\\Users\\alexa\\Documents\\College\\Physics\\Physics 25L\\Boltzmann_video_2.avi')`

Here is the complete traceback:
```
Traceback (most recent call last):

  File "<ipython-input-8-18236c661fe1>", line 1, in <module>
    v = pims.Video('C:\\Users\\alexa\\Documents\\College\\Physics\\Physics 25L\\Boltzmann_video_2.avi')

  File "C:\Users\alexa\Anaconda3\lib\site-packages\pims\pyav_reader.py", line 139, in __init__
    frame = next(_gen_frames(demuxer, self._stream.time_base))

  File "C:\Users\alexa\Anaconda3\lib\site-packages\pims\pyav_reader.py", line 54, in _gen_frames
    for packet in demuxer:

  File "av/container/input.pyx", line 88, in demux

  File "av/container/streams.pyx", line 50, in _flatten

TypeError: list indices must be integers or slices, not av.video.stream.VideoStream
```

Someone over at the trackpy section of github told me to check if this was a PyAv issue or a pims issue using:

```
import av

container = av.open(path_to_video)

for frame in container.decode(video = 0):
      frame.to_image().save('frame-04%d.jpd' % frame.index)
```

Which returned:

`deprecated pixel format used, make sure you did set range correctly`

**Comment by nkeim** [comment]
HI! Sorry for the long delay, and thanks for checking PyAv. The warning that it gave you is just a warning, not an error, so it should have worked. Are there files in your working directory? (That would be the directory you were running the script in, or, if you are using a notebook, it is usually the directory where the notebook is stored. It is not necessarily the directory where the movie is stored.)

**Comment by lyprince** [comment]
I am having this problem also. I had no problems with pims before, but after installing av this error is occurring. Both were installed with conda in python 3.5

**Comment by nkeim** [comment]
@lyprince Thanks. We are still trying to understand whether this is a pims issue or a PyAV/ffmpeg issue. Are you able to read the file using PyAV directly, as @caspervdw posted in [this previous discussion](https://github.com/soft-matter/trackpy/issues/502#issuecomment-394175672)?

**Comment by Britefury** [comment]
I've also had this problem. Fixed by downgrading (using conda) PyAV from v0.4 to 0.3.3.

**Comment by lyprince** [comment]
I am able to read the file using PyAV directly using @caspervdw 's code

**Comment by nkeim** [comment]
Thank you @Britefury and @lyprince ! This is very helpful.

It looks like the behavior of `Container.demux` changed in PyAV 0.4. Before it accepted one or more `Stream` instances; now it expects integers that index the streams.

pims only passes arguments to `demux` in `PyAVReaderTimed.__init__()`. Could you please check that you *can* read the file using `pims.PyAVReaderIndexed(<filename>)` instead? (This is also a workaround until we fix this.)

**Comment by Britefury** [comment]
@nkeim Yes, I can read the file using `PyAVReaderIndexed` but not `PyAVReaderTimed` when using PyAV 4.x.

**Comment by nkeim** [comment]
Thank you @alex-amvdor and @Britefury ! I renamed this issue and we will try to fix it for the next minor release (or if you want to try your hand with our help we would welcome that!). In the meantime it's good that there is a workaround with `PyAVReaderIndexed`.

@alex-amvdor the new method for converting to grayscale is documented here: http://soft-matter.github.io/pims/dev/pipelines.html . I have created https://github.com/soft-matter/trackpy/issues/505 so that this can be fixed.

**Comment by nkeim** [comment]
For reference:

- [Relevant documentation for the PyAV 0.4 API](https://mikeboers.github.io/PyAV/api/stream.html#av.container.streams.StreamContainer.get)
- [Previous code for `demux`](https://github.com/mikeboers/PyAV/blob/7d5d33192b2530b41497ff6ee196ad3fe8e65a2d/av/container/input.pyx)
- [New code for `get` (called by `demux`)](https://github.com/mikeboers/PyAV/blob/master/av/container/streams.pyx)

**Comment by caspervdw** [comment]
I think @Meehai solved this issue. Could one of you doublecheck?

**Comment by yoanisgil** [comment]
I'm still seeing this issue with version PIMS `0.4.1`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/ygil/.local/share/virtualenvs/videoapi-ylCl8OUW/lib/python3.7/site-packages/pims/pyav_reader.py", line 139, in __init__
>     frame = next(_gen_frames(demuxer, self._stream.time_base))
>   File "/Users/ygil/.local/share/virtualenvs/videoapi-ylCl8OUW/lib/python3.7/site-packages/pims/pyav_reader.py", line 54, in _gen_frames
>     for packet in demuxer:
>   File "av/container/input.pyx", line 97, in demux
>   File "av/container/streams.pyx", line 50, in _flatten
> TypeError: list indices must be integers or slices, not av.video.stream.VideoStream

And here is the output from `pip freeze`:
av==6.1.2
numpy==1.16.2
PIMS==0.4.1
six==1.12.0
slicerator==1.0.0

**Comment by marinamdecastro** [comment]
> I'm still seeing this issue with version PIMS `0.4.1`
> 
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "/Users/ygil/.local/share/virtualenvs/videoapi-ylCl8OUW/lib/python3.7/site-packages/pims/pyav_reader.py", line 139, in **init**
> > frame = next(_gen_frames(demuxer, self._stream.time_base))
> > File "/Users/ygil/.local/share/virtualenvs/videoapi-ylCl8OUW/lib/python3.7/site-packages/pims/pyav_reader.py", line 54, in _gen_frames
> > for packet in demuxer:
> > File "av/container/input.pyx", line 97, in demux
> > File "av/container/streams.pyx", line 50, in _flatten
> > TypeError: list indices must be integers or slices, not av.video.stream.VideoStream
> 
> And here is the output from `pip freeze`:
> av==6.1.2
> numpy==1.16.2
> PIMS==0.4.1
> six==1.12.0
> slicerator==1.0.0

So do I! Exact same error...

**Comment by ythomashu** [comment]
I'm having the same problem.
How do you install the pims development version?

**Comment by ythomashu** [comment]
I found pims.PyAVReaderIndexed worked with avi but not mp4 format (pims.Video worked with neither)

Here are all the error messages when I ran v = pims.PyAVReaderIndexed('c:/Users/test.mp4')

st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001
st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.

**Comment by GenevieveBuckley** [comment]
> 
> 
> I'm having the same problem.
> How do you install the pims development version?

The simplest way would be to uninstall your current version of pims, then:

```
pip install git+https://github.com/soft-matter/pims.git
```

Note: by default the pims installation only brings with it the dependencies `numpy`, `slicerator`, and `six`. If you need support for other packages (to support video functionality) like `av`, `moviepy`, `imageio-ffmpeg`, etc. you'll need to make sure you've installed those yourself. You can see the list of all possible dependencies for pims here: https://github.com/soft-matter/pims/blob/master/environment.yml
