### ISSUE TITLE
problem with Bioformats/jpype

### ISSUE THREAD

**Issue by mmdriscoll** [soft-matter/pims#298]
I am trying to open a .vsi (Olympus) file using pims.Bioformats, but I get the following error:

im = pims.Bioformats('/Users/mdriscoll/Desktop/silicasphere.vsi')
2018-06-18 15:12:03.211 python[21589:8926559] Apple AWT Java VM was loaded on first thread -- can't start AWT.
---------------------------------------------------------------------------
java.lang.InternalErrorPyRaisable         Traceback (most recent call last)
<ipython-input-2-3db2ea20725c> in <module>()
----> 1 im = pims.Bioformats('/Users/mdriscoll/Desktop/silicasphere.vsi')

/anaconda2/lib/python2.7/site-packages/pims/bioformats.pyc in __init__(self, filename, meta, java_memory, read_mode, series)
    380         # Set read mode. When auto, tryout fast and check the image size.
    381         if read_mode == 'auto':
--> 382             Jarr = self.rdr.openBytes(0)
    383             if isinstance(Jarr[:], np.ndarray):
    384                 read_mode = 'jpype'

java.lang.InternalErrorPyRaisable: java.lang.InternalError: Can't start the AWT because Java was started on the first thread.  Make sure StartOnFirstThread is not specified in your application's Info.plist or on the command line

**Comment by caspervdw** [comment]
@mmdriscoll  I have never seen this error, but it seems to be a JPype error. Either we use it wrong or there is an issue with jpype itself. Looking at https://stackoverflow.com/questions/11374211/jpype-cant-start-the-awt-because-java-was-started-on-the-first-thread , it seems that adding ` '-Djava.awt.headless=true'` to the `StartJVM` might be a solution. So over here: https://github.com/soft-matter/pims/blob/d45bedb43e88282449629caf0c040138ea727d50/pims/bioformats.py#L348

Could you give that a try?

**Comment by mmdriscoll** [comment]
this works - thanks!
---------------------------------------------------------------------------
Michelle Driscoll
Assistant Professor, Department of Physics & Astronomy
Northwestern University
office/lab: Tech F411/FG42
phone: 847-467-6708
driscollphysicslab.org<http://driscollphysicslab.org>

On Jun 29, 2018, at 3:14 PM, Casper van der Wel <notifications@github.com<mailto:notifications@github.com>> wrote:


@mmdriscoll<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mmdriscoll&d=DwMFaQ&c=yHlS04HhBraes5BQ9ueu5zKhE7rtNXt_d012z2PA6ws&r=UkUlxXPFbVY3PpiOJMANjaxuHtAlbGj6rmiiCdGuu0YZck3DyHoie9octr_bqoeE&m=hflpdBAMv7zTa6Ncax8qKkRRyme8WkiflndAlrgDhw4&s=ox9xvOl2bmKV_rYS4zqGCYtE_dNjxA0m-AuCF9OTNsE&e=> I have never seen this error, but it seems to be a JPype error. Either we use it wrong or there is an issue with jpype itself. Looking at https://stackoverflow.com/questions/11374211/jpype-cant-start-the-awt-because-java-was-started-on-the-first-thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__stackoverflow.com_questions_11374211_jpype-2Dcant-2Dstart-2Dthe-2Dawt-2Dbecause-2Djava-2Dwas-2Dstarted-2Don-2Dthe-2Dfirst-2Dthread&d=DwMFaQ&c=yHlS04HhBraes5BQ9ueu5zKhE7rtNXt_d012z2PA6ws&r=UkUlxXPFbVY3PpiOJMANjaxuHtAlbGj6rmiiCdGuu0YZck3DyHoie9octr_bqoeE&m=hflpdBAMv7zTa6Ncax8qKkRRyme8WkiflndAlrgDhw4&s=480BjQgroZ0WxjIbL1egm1WJ7bizNuW9M4i-jOwva0E&e=> , it seems that adding '-Djava.awt.headless=true' to the StartJVM might be a solution. So over here: https://github.com/soft-matter/pims/blob/d45bedb43e88282449629caf0c040138ea727d50/pims/bioformats.py#L348<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_soft-2Dmatter_pims_blob_d45bedb43e88282449629caf0c040138ea727d50_pims_bioformats.py-23L348&d=DwMFaQ&c=yHlS04HhBraes5BQ9ueu5zKhE7rtNXt_d012z2PA6ws&r=UkUlxXPFbVY3PpiOJMANjaxuHtAlbGj6rmiiCdGuu0YZck3DyHoie9octr_bqoeE&m=hflpdBAMv7zTa6Ncax8qKkRRyme8WkiflndAlrgDhw4&s=MwRWKOTSVJxbJqD5HCtjSHcPpgow0TYYLwwbMccYhFk&e=>

Could you give that a try?
