### ISSUE TITLE
Bundling pims with loci_tools.jar in python application

### ISSUE THREAD

**Issue by GenevieveBuckley** [soft-matter/pims#299]
I'm building a python application using pims ([bioformats.py](https://github.com/soft-matter/pims/blob/master/pims/bioformats.py)) to load image data. Is there a best practice for bundling both pims AND the loci_tools.jar dependency together?

Pyinstaller can [include files in the bundle](http://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-files-to-the-bundle) pretty easily, so I think the sticking point is teaching pims where to look for it. Is modifying the `_gen_jar_locations` function in [pims/bioformats.py](https://github.com/soft-matter/pims/blob/master/pims/bioformats.py) the best option here?

(Ideally, I'd also like to be able to bundle a more recent version of loci_tools.jar (or a specific version of my choice). Pims currently specifies version 5.7.0, which is nine months and six versions out of date now.)

**Comment by caspervdw** [comment]
If you like to bundle pims and bioformats in a single package, you can do so by putting `loci_tools.jar` right next to `bioformats.py`. That is the first place the program looks. So you do not need to modify any functions.

Including binary files inside a python distriubtion can be done using a `MANIFEST.in` file, like so: https://github.com/soft-matter/pims/blob/master/MANIFEST.in

Thanks for the heads up about the version, I could find a stable solution to get the latest version number automatically so we are stuck with bumping it every now and then.  You could call the `pims.bioformats._download_jar(version=xxx)` if you want to have a different version.

**Comment by caspervdw** [comment]
Ref #301

**Comment by GenevieveBuckley** [comment]
Great advice, thanks Casper!
