### ISSUE TITLE
Reassigning Ndimensions

### ISSUE THREAD

**Issue by ctr26** [soft-matter/pims#307]
Hi all,

I am currently loading a tiff stack in using pims, unfortunately the metadata suggests it's a time series not a z stack. Is there anyway of reassigning this in pims?  I've already tried this:

``reader = pims.open('./_data/stack_z-2cm.tif')

reader.bundle_axes = ["z", "y", "x"]
reader.iter_axis = "t"
#reader = pims.bioformats.BioformatsReader('./_data/stack_z-2cm.tif')
reader``

Thanks!

**Comment by caspervdw** [comment]
Sorry for not responding, I guess you already found a solution.
If not, please try:

    frames.bundle_axes = ‘tyx’
