### ISSUE TITLE
Pims not recognizing PyAV

### ISSUE THREAD

**Issue by irenepj97** [soft-matter/pims#311]
Hello, I am currently trying to use pims.Video in collaboration with TrackPy in order to track particles in a .avi file. Though I have conda-installed Pims and PyAV separately, after importing Pims in Jupyter Notebook and then calling pims.Video(), I get the error:
ImportError: This reader requires PyAV, MoviePy, or ImageIO.
Thus, it seems that Pims is not recognizing my installation of PyAV. I would appreciate any insight or assistance you could give me for resolving this issue.

**Comment by caspervdw** [comment]
It appears that PyAV is moving fast. Could you report your pyav and pims versions? Maybe installing pyav 0.4 would be a quick fix for you.

**Comment by caspervdw** [comment]
I checked out the newest PyAV and there seem to be no issues. Please provide some more info, or close the issue if it has been solved for you already.

**Comment by nkeim** [comment]
As of #313 pims is hopefully back in equilibrium with PyAV.
