### ISSUE TITLE
image.sc forum

### ISSUE THREAD

**Issue by joshmoore** [soft-matter/pims#323]
Comparing https://github.com/soft-matter/pims#core-contributors and https://forum.image.sc/users I didn't see an overlap so I thought I'd reach out and say "Hi". I personally try to follow this repo as much as I can (though I just noticed a few issues with Bio-Formats that I'd like to follow up on...), but in case there are any issues that require more immediate attention, feel free to post on https://forum.image.sc/tags/bio-formats

Additionally, I've just created a [`pims`-tag](https://forum.image.sc/tags/pims). If any specific questions arise that I know need to be thrown your way, I'll add them there.

All the best,
~Josh

**Comment by caspervdw** [comment]
Hi Josh, thanks for reaching out. I contributed the bioformats wrapper (through jpype) as part of my PhD 3-4 years ago, as well as the nd2 reader (pims_nd2). These worked well for me back then but I don’t really have the time anymore to maintain them actively.

It is good to hear they are still being used, apparently without too much out-of-dateness!
