### ISSUE TITLE
pims.Video()  waitting close forver

### ISSUE THREAD

**Issue by haoyiping** [soft-matter/pims#328]
sometimes when i use
`video = pims.Video(self.video_path)
 video.close()
`
this process waits to execute close finish
![image](https://user-images.githubusercontent.com/17242170/63832095-a57f9e80-c9a2-11e9-9798-3e4cf9f59c07.png)

when i kill process ffmpeg-linux64-
process can execute over it

**Comment by nkeim** [comment]
Closing since we don't have steps to reproduce, and ffmpeg support has changed in the development version.
