### ISSUE TITLE
Jpype1 0.7 breaks bioformat integration

### ISSUE THREAD

**Issue by MathieuLeocmach** [soft-matter/pims#330]
On a clean install, pims.open on a leica image file (.lif) was raising a Java error.
Thanks to this [issue on stackoverflow](https://stackoverflow.com/questions/56754718/runtimeerror-unable-to-start-jvm-because-of-deprecated-convertstrings), I tracked the problem down to the version of Jpype. Indeed Jpype1 0.7 was released in June 2019. As suggesed, I downgraded Jpype1 to previous version (0.6.3) and everything works fine now. There is probably some adaptation to make in pims to take into account the new Jpype version, or at least restrict the dependencies to versions strictly below 0.7.

**Comment by nkeim** [comment]
Has anyone (including @MathieuLeocmach ) had a chance to look into this? Is it just for certain file types? (I'm wondering why the Travis tests are still passing.)

**Comment by MathieuLeocmach** [comment]
I had no time to look more into this, sorry.
