### ISSUE TITLE
query frame rate?

### ISSUE THREAD

**Issue by bjarthur** [soft-matter/pims#337]
i need to index into a video at specific *times*, in seconds, not at specific frames.  for this i need to know the frame rate.  is there an API to get it?  currently i'm using:

```
import pims
v=pims.open(...)
v
Source: XXX.avi
Length: XXX frames
Frame Shape: (X, Y, T)
```

thanks!

**Comment by tacaswell** [comment]
It looks like some of the reader classes have a `frame_rate` property, but that is not universal.  In general, the way that the frame rate is encoded in the file meta-data can vary wildly between both formats and vendors so it is hard to reliably find it in the file.

The best path is probably to sort out how to get the frame rate out of the meta-data and then do the time -> frame number conversion externally to PIMS.

**Comment by bjarthur** [comment]
thanks for the quick reply.

unfortunately, the metadata attribute is empty in the example i gave above when used with an h.264 mp4 file.  the frame number is there though.

```
>>> v[0].metadata
{}
>>> v[0].frame_no
0
```

is there another way to access it?

**Comment by tacaswell** [comment]
You may need to extend the reader to extract additional meta-data then.

**Comment by nkeim** [comment]
Is this functionality for mp4 provided by PyAVReaderTimed?

**Comment by danielballan** [comment]
Yes. @bjarthur, you were accessing the metadata on a specific _frame_. The frame rate is meta about the whole _series_ of frames, and it is a property of `v`. Try:

```py
v.frame_rate
```

which should access [this property](https://github.com/soft-matter/pims/blob/c7a535842b5719fb950419431cca7cd56fb27598/pims/pyav_reader.py#L170-L172).

**Comment by bjarthur** [comment]
thanks @danielballan !  `v.frame_rate` works.  my stupid.
