### ISSUE TITLE
Read dv metadata and Write ome tiff 

### ISSUE THREAD

**Issue by joaomamede** [soft-matter/pims#348]
Sorry if it 's not the proper place, it's not an issue with PIMS but more of a request.

I have .dv files that were acquired with an OMX-SR that has 3 cameras. The registration process failed in a given experiment and I need to register the images and save them to an ome.tiff for later analysis. 

This is the script I made opening with pims and then fixing the image and save if with tifffile.
My question is how can I get the metadata replicated correctly from pims to the tifffile save? I tried many things (latest attempt in the attached file). But the metadata is never written correctly.

Thank you.

[fixXY_withZ_savewithpims.zip](https://github.com/soft-matter/pims/files/4569611/fixXY_withZ_savewithpims.zip)

[fixXY_savewithpims.zip](https://github.com/soft-matter/pims/files/4569609/fixXY_savewithpims.zip)

**Comment by GenevieveBuckley** [comment]
If your question is about how to write metadata with `tifffile` it's probably better to ask it over at https://github.com/cgohlke/tifffile

The nice thing is that basically the entire functionality is contained in a single file [tifffile.py](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py). I'm not entirely sure what "metadata replicated correctly" means for you, but it's probably worth taking a look at the docstring for the [`tifffile.save()` function](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L876) to see what options for saving different types of metadata are available. 

There are also some good examples of saving tiff files with metadata among the examples included in the module level docstring (like [this example](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L340)). I hope this gets you unstuck!

**Comment by joaomamede** [comment]
Thank you!
I also contacted the tifffile developer.
My question about replicating is. When Pims extract the Metadata, is it possible just to replicate/extract the original xml into a variable? 

In my case I'll keep the image properties the same, so I would just need to save it again.

**Comment by GenevieveBuckley** [comment]
The java bioformats MetadataRetrieve class is wrapped by pims. It seems the link from the [docs](http://soft-matter.github.io/pims/v0.4/bioformats.html) is broken, but this looks like the page it should be pointing to: https://www-legacy.openmicroscopy.org/site/support/bio-formats5.1/developers/cpp/tutorial.html

**Comment by joaomamede** [comment]
Very cool, thank you.

**Comment by joaomamede** [comment]
frames = pims.bioformats.BioformatsReader(fname)
xml = frames._metadata.dumpXML() #basically replicates the whole original XML.

from Tifffile import TiffWriter
with TiffWriter('temp.tif', bigtiff=True) as tif:
    for i in range(data.shape[0]):
        tif.save(data[i], compress=6, description = xml, photometric='minisblack', metadata = {'insert' : 'randomstuff')

Should do the trick.

**Comment by joaomamede** [comment]
This works:

```
frames = pims.open('example.dv')
a = str(frames._metadata.dumpXML())

import aicsimageio.vendor.omexml as omexmlClass
xml = omexmlClass.OMEXML(a)

tifstack = tf.TiffWriter(stackfile, bigtiff=False,imagej=False)
tifstack.save(res.astype(np.uint16),
#                         compression='ZLIB',
              compression=9,
    description = xml.to_xml(),
    photometric='minisblack',
    metadata= None,
    contiguous=False
    )

```
