### ISSUE TITLE
don't load GUI on import

### ISSUE THREAD

**Issue by bjarthur** [soft-matter/pims#351]
on the 30 april 2020 master branch of pims i get the following warnings on import:

```
$ python3
Python 3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> import imageio
>>> import pims
Unable to init server: Could not connect: Connection refused

(.:17522): Gtk-WARNING **: 07:39:25.629: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to init server: Could not connect: Connection refused

(.:17522): Gdk-CRITICAL **: 07:39:25.630: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
>>> pims.__version__
'0+unknown'
```

it was [suggested](https://github.com/soft-matter/pims/issues/332#issuecomment-621999795) that this is because pims is importing matplotlib, and that having imageio installed would help.  the latter does not.

note that these warning are emitted whether or not matplotlib and imageio are explicitly imported, as they are above, or not.

this is all within a singularity container.

**Comment by caspervdw** [comment]
Thanks for raising this issue. Apart from this, the long wait time on `import pims` always bothered me.

Maybe we can use an approach like this https://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it

**Comment by bjarthur** [comment]
oof, my bad.  problem was that GTK is the default matplotlib backend, which i did not have installed.  changing it to Tk, which i did install, results in no errors:

```
>>> import matplotlib as mpl
>>> mpl.use('TkAgg')
>>> import pims
```

sorry for the noise.

**Comment by nkeim** [comment]
No problem! The behavior of loading every dependency is still not great. It needs to change, in the long run.

**Comment by gmazzamuto** [comment]
Hi all, when importing pims on a remote machine (no display server) I still get these warnings:
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(.:2484): Gdk-CRITICAL **: 20:13:16.214: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
```

This is due to `import matplotlib.pyplot as plt` in `display.py`. Perhaps it is worth setting the matplotlib backend just before importing pyplot to suppress these warnings.

```py
import matplotlib as mpl
mpl.use('Agg')
```

Just an idea, thank you!
