### ISSUE TITLE
Update pims documentation & code re: deprecated scipy.ndimage.imread

### ISSUE THREAD

**Issue by GenevieveBuckley** [soft-matter/pims#355]
The [pims installation docs](https://github.com/soft-matter/pims/blob/master/doc/source/install.rst) say that you need either scikit-image, matplotlib, or scipy if you want to do basic image reading. This isn't true anymore, scipy [deprecated `imread` in 2017](https://github.com/scipy/scipy/pull/7869) and should be removed from that list.

Pims also still refers to the `scipy.ndimage.imread` function [in line 33 of image_sequence.py](https://github.com/soft-matter/pims/blob/cd40d4edcf1379d800e03273f8ffd63e097ec0c6/pims/image_sequence.py#L33).

**Comment by nkeim** [comment]
Thank you @GenevieveBuckley ! Even though I was hoping that we would not make any more changes before v0.5, it is the perfect opportunity to fix this, because removing scipy support will no doubt break some existing code.
