### ISSUE TITLE
Modifing frame.

### ISSUE THREAD

**Issue by khoroshyy** [soft-matter/pims#367]
Hi there.
It is not an issue, more usage question.
How do I modify loaded frame?
If I try in this way I get an error.

frames1[25] = filters.gaussian(frames1[25], sigma=1,)
TypeError: 'TiffStack_tifffile' object does not support item assignment

Thanks.
Petro.

**Comment by nkeim** [comment]
pims does not store images in memory; it only reads them from disk. So I don't see this feature as a high priority to add to pims, since in most cases it would be permanently altering your experimental data.

Perhaps pims pipelines are what you are looking for?

**Comment by khoroshyy** [comment]
Thanks. Yes pipelines  will be OK for  me.
