### ISSUE TITLE
cine.py broken by python 3.9+

### ISSUE THREAD

**Issue by leonavery** [soft-matter/pims#402]
In python 3.9+, `Iterable` can no longer be imported directly from `collections`. It has been moved to `collections.abc`. Thus this line:

     from collections import Iterable

in `cine.py` is broken. It needs to be 

    from collections.abc import Iterable

presumably conditional on the python version.

**Comment by marscher** [comment]
It seems this has been fixed on master already, when can users expect a new release?

**Comment by nkeim** [comment]
Closing now that #412 is active.
