### ISSUE TITLE
v0.6.0 gives error: NotImplementedError: Do not know how to deal with infinite readers

### ISSUE THREAD

**Issue by fcakyon** [soft-matter/pims#413]
## summary:
While reading an mp4 file having the following error: 
```bash
NotImplementedError: Do not know how to deal with infinite readers
```

## steps to recreate:
System: ubuntu 18.04
Download the mp4 file: https://drive.google.com/file/d/1Ic7K-OAMCGNAShav9Ywui6qwkXKzWgo-/view?usp=sharing
```bash
pip install pims==0.6.0 imageio-ffmpeg==0.4.7
```
```python
video_reader = pims.Video(clip_path)
```

## temporary fix:
pims v0.5.0 doesnt give this error.
```bash
pip install pims==0.5.0 imageio-ffmpeg==0.4.7
```

**Comment by jmdelahanty** [comment]
Also running into this error today with v0.6.0

**Comment by GenevieveBuckley** [comment]
I've experienced the same thing. I think it can be fixed with something like https://github.com/soft-matter/pims/pull/415
