### ISSUE TITLE
Possible to pickle / serialize the index for PyAVReaderIndexed

### ISSUE THREAD

**Issue by MatusGasparik** [soft-matter/pims#438]
https://github.com/soft-matter/pims/blob/5ec734df60cfc7bc449bdd70bb3e4b90bccb026a/pims/pyav_reader.py#L274

I have a need to access the individual frames in a video randomly and I use the `PyAVReaderIndexed` for this, which works nicely.

Since the instantiation can take substantial amount of time (depending on the length and resolution of the video) I was wondering whether it would be possible to "pickle" the index, once generated.

Any ideas? (Note: I'm not familiar with how PyAV works...)

**Comment by horsto** [comment]
I had a similar question and I am wondering whether the substantial amount of time it takes is related somehow to https://github.com/soft-matter/pims/issues/425 Is there any way to speed index building up in the first place?

**Comment by MatusGasparik** [comment]
I had a look into the source code. The `toc` attribute / property does it. Since I need a repeated (random) access to the video frames it seems feasible to pickle the `toc` generated on the first instantiation...
